# Sử dụng base image OpenJDK 21
FROM openjdk:21-jdk-slim

# Cài đặt Node.js để build Tailwind CSS
RUN apt-get update && apt-get install -y nodejs npm

# Thiết lập thư mục làm việc trong container
WORKDIR /app

# Copy toàn bộ mã nguồn của ứng dụng vào container
COPY . .

# Cài đặt các dependency cho Tailwind
RUN npm install

# Build Tailwind CSS
RUN npm run build:css

# Build ứng dụng Spring Boot
RUN ./mvnw clean package -DskipTests

# Expose cổng 8080 để truy cập vào ứng dụng
EXPOSE 8080

# Lệnh để chạy ứng dụng Spring Boot khi container được khởi động
ENTRYPOINT ["java", "-jar", "/app/target/ecommerce-app.jar"]
